"""Fixed, reproducible fixtures for the representative synthetic drilling dataset."""

from math import asin, atan2, cos, degrees, radians, sin
from typing import Any, Dict, List, Tuple

DATASET_LABEL = "Representative Synthetic Demo Data"
EARTH_RADIUS_KM = 6371.0088

FIELD_ORIGINS = {
    "Upper-Assam-Demo": (27.45, 95.20),
    "Riverbend-Demo": (27.95, 94.00),
    "North-Block-Demo": (28.45, 96.45),
}

FORMATIONS: List[Dict[str, Any]] = [
    {
        "key": "upper", "name": "Upper Shale", "aliases": ["upper shale"],
        "lithology": "silty shale", "geological_zone": "Upper Shale interval", "reservoir_zone": None,
        "pressure_indicator": "typical", "porosity_percent": None, "permeability_md": None,
    },
    {
        "key": "y", "name": "Y Shale", "aliases": ["y formation", "y-shale"],
        "lithology": "shale with thin silt beds", "geological_zone": "Y Shale interval", "reservoir_zone": None,
        "pressure_indicator": "typical", "porosity_percent": None, "permeability_md": None,
    },
    {
        "key": "z", "name": "Z Sandstone", "aliases": ["z formation", "z-sand"],
        "lithology": "fine-grained sandstone", "geological_zone": "Z Sandstone interval",
        "reservoir_zone": "Z sandstone unit", "pressure_indicator": "typical",
        "porosity_percent": 14.0, "permeability_md": 45.0,
    },
    {
        "key": "x", "name": "X Formation", "aliases": ["x formation", "x-fm"],
        "lithology": "interbedded sandstone and shale", "geological_zone": "X Formation interval",
        "reservoir_zone": "X sandstone unit", "pressure_indicator": "review_indicator",
        "porosity_percent": 16.0, "permeability_md": 60.0,
    },
    {
        "key": "basal", "name": "Basal Sandstone", "aliases": ["basal sand"],
        "lithology": "fine to medium sandstone", "geological_zone": "Basal Sandstone interval",
        "reservoir_zone": "Basal sandstone unit", "pressure_indicator": "typical",
        "porosity_percent": 13.0, "permeability_md": 32.0,
    },
]

# Deterministic snapshots for the synthetic comparison and simulated feed. Units are
# explicit and values are rounded representative examples, not operational setpoints.
DRILLING_MEASUREMENT_FIXTURES: List[Dict[str, Any]] = [
    {"well": "ANB-01", "at": "2026-10-03T10:00:00Z", "md": 2842, "tvd": 2602, "mw": 1.16, "ecd": 1.19, "rop": 12.0, "wob": 65, "rpm": 100, "torque": 8.5, "spp": 14.5, "inc": 18, "azi": 45, "casing": 2490},
    {"well": "ANB-01", "at": "2026-10-03T10:05:00Z", "md": 2850, "tvd": 2610, "mw": 1.16, "ecd": 1.19, "rop": 11.5, "wob": 65, "rpm": 100, "torque": 8.7, "spp": 14.6, "inc": 18, "azi": 45, "casing": 2490},
    {"well": "ANB-01", "at": "2026-10-03T10:10:00Z", "md": 2858, "tvd": 2617, "mw": 1.16, "ecd": 1.20, "rop": 10.8, "wob": 66, "rpm": 100, "torque": 8.9, "spp": 14.7, "inc": 18, "azi": 45, "casing": 2490},
    {"well": "ANB-01", "at": "2026-10-03T10:15:00Z", "md": 2865, "tvd": 2624, "mw": 1.16, "ecd": 1.20, "rop": 10.2, "wob": 66, "rpm": 100, "torque": 9.1, "spp": 14.8, "inc": 18, "azi": 45, "casing": 2490},
    {"well": "ANB-01", "at": "2026-10-03T10:20:00Z", "md": 2875, "tvd": 2633, "mw": 1.17, "ecd": 1.20, "rop": 9.8, "wob": 66, "rpm": 100, "torque": 9.0, "spp": 14.8, "inc": 18, "azi": 45, "casing": 2490},
    {"well": "ANB-02", "at": "2024-07-14T08:15:00Z", "md": 2865, "tvd": 2616, "mw": 1.17, "ecd": 1.20, "rop": 10.0, "wob": 68, "rpm": 100, "torque": 8.8, "spp": 14.7, "inc": 19, "azi": 47, "casing": 2520},
    {"well": "ANB-03", "at": "2023-05-22T13:05:00Z", "md": 2830, "tvd": 2589, "mw": 1.16, "ecd": 1.19, "rop": 13.0, "wob": 63, "rpm": 105, "torque": 10.2, "spp": 14.6, "inc": 20, "azi": 43, "casing": 2485},
    {"well": "ANB-04", "at": "2022-07-09T02:10:00Z", "md": 2875, "tvd": 2627, "mw": 1.17, "ecd": 1.20, "rop": 9.5, "wob": 68, "rpm": 100, "torque": 8.9, "spp": 14.9, "inc": 17, "azi": 46, "casing": 2510},
    {"well": "ANB-05", "at": "2023-06-18T19:40:00Z", "md": 2235, "tvd": 2043, "mw": 1.12, "ecd": 1.15, "rop": 15.0, "wob": 58, "rpm": 105, "torque": 7.2, "spp": 13.5, "inc": 16, "azi": 40, "casing": 1900},
    {"well": "ANB-06", "at": "2026-10-03T10:00:00Z", "md": 1910, "tvd": 1752, "mw": 1.13, "ecd": 1.16, "rop": 13.0, "wob": 60, "rpm": 100, "torque": 7.8, "spp": 13.8, "inc": 21, "azi": 92, "casing": 1810},
    {"well": "ANB-06", "at": "2026-10-03T10:05:00Z", "md": 1920, "tvd": 1761, "mw": 1.13, "ecd": 1.16, "rop": 12.0, "wob": 60, "rpm": 100, "torque": 8.0, "spp": 13.9, "inc": 21, "azi": 92, "casing": 1810},
    {"well": "ANB-06", "at": "2026-10-03T10:10:00Z", "md": 1928, "tvd": 1768, "mw": 1.13, "ecd": 1.17, "rop": 10.0, "wob": 61, "rpm": 100, "torque": 8.2, "spp": 14.0, "inc": 21, "azi": 92, "casing": 1810},
    {"well": "ANB-07", "at": "2023-02-12T09:20:00Z", "md": 1932, "tvd": 1774, "mw": 1.13, "ecd": 1.17, "rop": 0.0, "wob": 0, "rpm": 0, "torque": 12.0, "spp": 14.0, "inc": 20, "azi": 94, "casing": 1830},
    {"well": "ANB-08", "at": "2026-10-03T10:00:00Z", "md": 1538, "tvd": 1409, "mw": 1.11, "ecd": 1.14, "rop": 15.0, "wob": 55, "rpm": 105, "torque": 6.8, "spp": 12.8, "inc": 14, "azi": 210, "casing": 1480},
    {"well": "ANB-08", "at": "2026-10-03T10:05:00Z", "md": 1548, "tvd": 1418, "mw": 1.11, "ecd": 1.14, "rop": 14.0, "wob": 55, "rpm": 105, "torque": 6.9, "spp": 12.9, "inc": 14, "azi": 210, "casing": 1480},
    {"well": "ANB-08", "at": "2026-10-03T10:10:00Z", "md": 1558, "tvd": 1427, "mw": 1.11, "ecd": 1.15, "rop": 13.0, "wob": 55, "rpm": 105, "torque": 7.0, "spp": 13.0, "inc": 14, "azi": 210, "casing": 1480},
    {"well": "ANB-09", "at": "2024-10-26T05:55:00Z", "md": 1560, "tvd": 1438, "mw": 1.11, "ecd": 1.15, "rop": 0.0, "wob": 0, "rpm": 0, "torque": 6.5, "spp": 13.1, "inc": 14, "azi": 208, "casing": 1510, "cementing": "Synthetic record: cement returns and follow-up evaluation noted in source event."},
    {"well": "ANB-10", "at": "2026-10-03T10:00:00Z", "md": 2490, "tvd": 2285, "mw": 1.15, "ecd": 1.18, "rop": 12.0, "wob": 62, "rpm": 100, "torque": 8.0, "spp": 14.0, "inc": 22, "azi": 275, "casing": 2410},
]


def destination_point(latitude: float, longitude: float, distance_km: float, bearing_deg: float) -> Tuple[float, float]:
    """Return a deterministic WGS84-like destination for the fixture map."""
    angular_distance = distance_km / EARTH_RADIUS_KM
    bearing = radians(bearing_deg)
    lat1 = radians(latitude)
    lon1 = radians(longitude)
    lat2 = asin(sin(lat1) * cos(angular_distance) + cos(lat1) * sin(angular_distance) * cos(bearing))
    lon2 = lon1 + atan2(
        sin(bearing) * sin(angular_distance) * cos(lat1),
        cos(angular_distance) - sin(lat1) * sin(lat2),
    )
    return round(degrees(lat2), 6), round(degrees(lon2), 6)


WELL_FIXTURES: List[Dict[str, Any]] = [
    {
        "key": "ANB-01",
        "field": "Upper-Assam-Demo",
        "location": "origin",
        "well_name": "ANB-01",
        "role": "active",
        "status": "drilling",
        "spud_date": "2026-07-02",
        "completion_date": None,
        "total_depth": 3400,
        "current_depth": 2842,
        "current_formation": "x",
        "formations": [
            ("upper", 0, 1600),
            ("y", 1600, 2250),
            ("z", 2250, 2490),
            ("x", 2490, 3200),
            ("basal", 3200, 3400),
        ],
    },
    {
        "key": "ANB-02",
        "field": "Upper-Assam-Demo",
        "offset": ("Upper-Assam-Demo", 4.2, 35),
        "well_name": "ANB-02",
        "role": "offset",
        "status": "completed",
        "spud_date": "2024-06-12",
        "completion_date": "2024-11-20",
        "total_depth": 3420,
        "current_depth": 3420,
        "current_formation": "basal",
        "formations": [
            ("upper", 0, 1600),
            ("y", 1600, 2250),
            ("z", 2250, 2490),
            ("x", 2490, 3200),
            ("basal", 3200, 3420),
        ],
    },
    {
        "key": "ANB-03",
        "field": "Upper-Assam-Demo",
        "offset": ("Upper-Assam-Demo", 6.1, 145),
        "well_name": "ANB-03",
        "role": "offset",
        "status": "completed",
        "spud_date": "2023-02-15",
        "completion_date": "2023-07-01",
        "total_depth": 3310,
        "current_depth": 3310,
        "current_formation": "basal",
        "formations": [
            ("upper", 0, 1600),
            ("y", 1600, 2250),
            ("z", 2250, 2490),
            ("x", 2490, 3200),
            ("basal", 3200, 3310),
        ],
    },
    {
        "key": "ANB-04",
        "field": "Upper-Assam-Demo",
        "offset": ("Upper-Assam-Demo", 7.4, 260),
        "well_name": "ANB-04",
        "role": "offset",
        "status": "completed",
        "spud_date": "2022-04-03",
        "completion_date": "2022-09-18",
        "total_depth": 3375,
        "current_depth": 3375,
        "current_formation": "basal",
        "formations": [
            ("upper", 0, 1600),
            ("y", 1600, 2250),
            ("z", 2250, 2490),
            ("x", 2490, 3200),
            ("basal", 3200, 3375),
        ],
    },
    {
        "key": "ANB-05",
        "field": "Upper-Assam-Demo",
        "offset": ("Upper-Assam-Demo", 11.2, 330),
        "well_name": "ANB-05",
        "role": "offset",
        "status": "completed",
        "spud_date": "2023-05-01",
        "completion_date": "2023-09-20",
        "total_depth": 3280,
        "current_depth": 3280,
        "current_formation": "basal",
        "formations": [
            ("upper", 0, 1600),
            ("y", 1600, 2250),
            ("z", 2250, 2490),
            ("x", 2490, 3200),
            ("basal", 3200, 3280),
        ],
    },
    {
        "key": "ANB-06",
        "field": "Riverbend-Demo",
        "location": "origin",
        "well_name": "ANB-06",
        "role": "active",
        "status": "drilling",
        "spud_date": "2026-08-06",
        "completion_date": None,
        "total_depth": 3350,
        "current_depth": 1910,
        "current_formation": "z",
        "formations": [("upper", 0, 800), ("y", 800, 1850), ("z", 1850, 2520), ("basal", 2520, 3350)],
    },
    {
        "key": "ANB-07",
        "field": "Riverbend-Demo",
        "offset": ("Riverbend-Demo", 3.4, 80),
        "well_name": "ANB-07",
        "role": "offset",
        "status": "completed",
        "spud_date": "2022-11-05",
        "completion_date": "2023-04-16",
        "total_depth": 3290,
        "current_depth": 3290,
        "current_formation": "basal",
        "formations": [("upper", 0, 800), ("y", 800, 1850), ("z", 1850, 2520), ("basal", 2520, 3290)],
    },
    {
        "key": "ANB-08",
        "field": "North-Block-Demo",
        "location": "origin",
        "well_name": "ANB-08",
        "role": "active",
        "status": "drilling",
        "spud_date": "2026-08-22",
        "completion_date": None,
        "total_depth": 3220,
        "current_depth": 1538,
        "current_formation": "y",
        "formations": [("upper", 0, 1100), ("y", 1100, 1650), ("z", 1650, 2220), ("basal", 2220, 3220)],
    },
    {
        "key": "ANB-09",
        "field": "North-Block-Demo",
        "offset": ("North-Block-Demo", 2.8, 45),
        "well_name": "ANB-09",
        "role": "offset",
        "status": "completed",
        "spud_date": "2024-08-12",
        "completion_date": "2024-12-15",
        "total_depth": 3210,
        "current_depth": 3210,
        "current_formation": "basal",
        "formations": [("upper", 0, 1100), ("y", 1100, 1650), ("z", 1650, 2220), ("basal", 2220, 3210)],
    },
    {
        "key": "ANB-10",
        "field": "North-Block-Demo",
        "offset": ("North-Block-Demo", 5.5, 235),
        "well_name": "ANB-10",
        "role": "active",
        "status": "drilling",
        "spud_date": "2026-09-05",
        "completion_date": None,
        "total_depth": 3250,
        "current_depth": 2490,
        "current_formation": "basal",
        "formations": [("upper", 0, 1100), ("y", 1100, 1650), ("z", 1650, 2220), ("basal", 2220, 3250)],
    },
]


def build_well_fixtures() -> List[Dict[str, Any]]:
    """Copy well fixtures and generate precise, deterministic offset coordinates."""
    result = []
    for fixture in WELL_FIXTURES:
        row = dict(fixture)
        if row.get("location") == "origin":
            row["coordinates"] = FIELD_ORIGINS[row["field"]]
        else:
            field, distance_km, bearing = row["offset"]
            row["coordinates"] = destination_point(*FIELD_ORIGINS[field], distance_km, bearing)
        result.append(row)
    return result


DOCUMENT_FIXTURES: Dict[str, Dict[str, Any]] = {
    "ANB-01": {"filename": "DDR-ANB-01-2026-09.pdf", "type": "daily_drilling_report", "pages": 28},
    "ANB-02": {"filename": "DDR-ANB-02-2024-07.pdf", "type": "daily_drilling_report", "pages": 34},
    "ANB-03": {"filename": "WCR-ANB-03.pdf", "type": "final_well_report", "pages": 86},
    "ANB-04": {"filename": "EOWR-ANB-04.pdf", "type": "final_well_report", "pages": 94},
    "ANB-05": {"filename": "DDR-ANB-05-2023-06.pdf", "type": "daily_drilling_report", "pages": 31},
    "ANB-06": {"filename": "DDR-ANB-06-2026-09.pdf", "type": "daily_drilling_report", "pages": 19},
    "ANB-07": {"filename": "EOWR-ANB-07.pdf", "type": "final_well_report", "pages": 77},
    "ANB-08": {"filename": "DDR-ANB-08-2026-09.pdf", "type": "daily_drilling_report", "pages": 18},
    "ANB-09": {"filename": "DDR-ANB-09-2024-11.pdf", "type": "daily_drilling_report", "pages": 36},
    "ANB-10": {"filename": "DDR-ANB-10-2026-10.pdf", "type": "daily_drilling_report", "pages": 12},
}


EVENT_FIXTURES: List[Dict[str, Any]] = [
    {
        "key": "ANB-01-npt-2382",
        "well": "ANB-01",
        "type": "npt_event",
        "title": "Connection-related non-productive time in Z Sandstone",
        "description": "Representative synthetic report records a connection delay above X Formation.",
        "md": 2382,
        "tvd": 2168,
        "formation": "z",
        "date": "2026-09-03T10:20:00Z",
        "consequence": "A short operational delay was recorded before drilling resumed.",
        "mitigation": "The crew completed the connection checks and resumed the planned sequence.",
        "severity": "low",
        "page": 7,
        "confidence": 0.97,
        "evidence": "Representative Synthetic Demo Data: connection delay recorded at 2,382 m in Z Sandstone.",
    },
    {
        "key": "ANB-01-instability-2020",
        "well": "ANB-01",
        "type": "wellbore_instability",
        "title": "Minor cavings noted in Y Shale",
        "description": "A synthetic earlier interval records intermittent cavings while drilling Y Shale.",
        "md": 2020,
        "tvd": 1884,
        "formation": "y",
        "date": "2026-08-25T04:40:00Z",
        "consequence": "Additional circulation time was recorded.",
        "mitigation": "The report notes a circulation and hole-cleaning response before continuing.",
        "severity": "low",
        "page": 11,
        "confidence": 0.91,
        "evidence": "Representative Synthetic Demo Data: cavings noted near 2,020 m in Y Shale.",
    },
    {
        "key": "ANB-02-loss-2865",
        "well": "ANB-02",
        "type": "lost_circulation",
        "title": "Partial lost circulation in X Formation",
        "description": "Partial returns were recorded while drilling the X Formation interval.",
        "md": 2865,
        "tvd": 2616,
        "formation": "x",
        "date": "2024-07-14T08:15:00Z",
        "consequence": "Reduced returns and a short circulation pause were documented.",
        "mitigation": "The synthetic report records a loss-control material treatment and subsequent return monitoring.",
        "severity": "medium",
        "page": 3,
        "confidence": 0.96,
        "evidence": "Representative Synthetic Demo Data: partial circulation losses at 2,865 m in X Formation; mitigation and return checks noted.",
    },
    {
        "key": "ANB-02-mud-adjust-2868",
        "well": "ANB-02",
        "type": "mud_weight_adjustment",
        "title": "Mud weight adjustment after flow checks",
        "description": "The report records a mud-weight change following a flow and pressure review in X Formation.",
        "md": 2868,
        "tvd": 2619,
        "formation": "x",
        "date": "2024-07-14T16:30:00Z",
        "consequence": "The recorded operation paused briefly for fluid-property checks.",
        "mitigation": "The crew documented an adjustment and repeated flow checks; no independent prescription is implied.",
        "severity": "low",
        "page": 4,
        "confidence": 0.94,
        "evidence": "Representative Synthetic Demo Data: mud-weight adjustment and repeat flow checks documented near 2,868 m.",
    },
    {
        "key": "ANB-03-torque-2830",
        "well": "ANB-03",
        "type": "torque_spike",
        "title": "Torque spike while drilling X Formation",
        "description": "A short-lived torque increase was recorded close to the X Formation top.",
        "md": 2830,
        "tvd": 2589,
        "formation": "x",
        "date": "2023-05-22T13:05:00Z",
        "consequence": "Drilling parameters were reviewed before the interval was continued.",
        "mitigation": "The report describes a pause, parameter review, and monitored resumption.",
        "severity": "medium",
        "page": 22,
        "confidence": 0.95,
        "evidence": "Representative Synthetic Demo Data: torque increase observed at 2,830 m in X Formation; review and monitored resumption recorded.",
    },
    {
        "key": "ANB-03-drag-2818",
        "well": "ANB-03",
        "type": "drag_increase",
        "title": "Elevated pickup drag in X Formation",
        "description": "Pickup drag increased over several connections in the same interval.",
        "md": 2818,
        "tvd": 2578,
        "formation": "x",
        "date": "2023-05-22T17:45:00Z",
        "consequence": "Additional circulation time was recorded.",
        "mitigation": "The crew documented circulation and a monitored short trip before proceeding.",
        "severity": "medium",
        "page": 23,
        "confidence": 0.92,
        "evidence": "Representative Synthetic Demo Data: pickup drag trend increased near 2,818 m; circulation and monitored movement noted.",
    },
    {
        "key": "ANB-03-cleaning-2780",
        "well": "ANB-03",
        "type": "hole_cleaning_issue",
        "title": "Hole-cleaning concern approaching X Formation",
        "description": "Cuttings loading was noted during a synthetic interval review immediately above X Formation.",
        "md": 2460,
        "tvd": 2250,
        "formation": "z",
        "date": "2023-05-20T06:30:00Z",
        "consequence": "A short delay was attributed to additional hole cleaning.",
        "mitigation": "The historical record notes circulation and returns monitoring.",
        "severity": "low",
        "page": 18,
        "confidence": 0.90,
        "evidence": "Representative Synthetic Demo Data: cuttings loading noted at 2,460 m in Z Sandstone; circulation response recorded.",
    },
    {
        "key": "ANB-04-loss-2875",
        "well": "ANB-04",
        "type": "lost_circulation",
        "title": "Mud loss reported in X Formation",
        "description": "A separate offset record notes mud loss deeper in X Formation.",
        "md": 2875,
        "tvd": 2627,
        "formation": "x",
        "date": "2022-07-09T02:10:00Z",
        "consequence": "Reduced returns and a controlled pause were documented.",
        "mitigation": "The report describes a loss-control treatment followed by monitored circulation.",
        "severity": "medium",
        "page": 41,
        "confidence": 0.97,
        "evidence": "Representative Synthetic Demo Data: mud loss at 2,875 m in X Formation; loss-control treatment and return monitoring recorded.",
    },
    {
        "key": "ANB-04-casing-2350",
        "well": "ANB-04",
        "type": "casing_issue",
        "title": "Casing running delay near Z Sandstone shoe",
        "description": "A synthetic completion record notes elevated running resistance during a casing operation.",
        "md": 2350,
        "tvd": 2150,
        "formation": "z",
        "date": "2022-06-28T11:00:00Z",
        "consequence": "The casing operation took additional time.",
        "mitigation": "The crew documented a controlled pullback, circulation, and resumed casing run.",
        "severity": "medium",
        "page": 32,
        "confidence": 0.89,
        "evidence": "Representative Synthetic Demo Data: casing running resistance noted near 2,350 m; controlled response described.",
    },
    {
        "key": "ANB-04-instability-2030",
        "well": "ANB-04",
        "type": "wellbore_instability",
        "title": "Cavings and tight spots in Y Shale",
        "description": "The end-of-well summary records cavings and intermittent tight spots in Y Shale.",
        "md": 2030,
        "tvd": 1852,
        "formation": "y",
        "date": "2022-06-13T07:25:00Z",
        "consequence": "Extra circulation and reaming time was recorded.",
        "mitigation": "The report describes circulation, conditioning, and monitored reaming.",
        "severity": "medium",
        "page": 27,
        "confidence": 0.93,
        "evidence": "Representative Synthetic Demo Data: cavings and tight spots at 2,030 m in Y Shale; conditioning response documented.",
    },
    {
        "key": "ANB-05-kick-2235",
        "well": "ANB-05",
        "type": "kick_influx",
        "title": "Flow check identified an influx indication",
        "description": "A synthetic daily report notes a flow-check indication while drilling Y Shale.",
        "md": 2235,
        "tvd": 2043,
        "formation": "y",
        "date": "2023-06-18T19:40:00Z",
        "consequence": "The operation was paused for the recorded well-control response.",
        "mitigation": "The source summary records a controlled shut-in and circulation response by the crew.",
        "severity": "high",
        "page": 12,
        "confidence": 0.90,
        "evidence": "Representative Synthetic Demo Data: flow-check influx indication at 2,235 m in Y Shale; response sequence referenced.",
    },
    {
        "key": "ANB-05-overpressure-2190",
        "well": "ANB-05",
        "type": "overpressure_signal",
        "title": "Elevated pressure trend noted in Y Shale",
        "description": "A pressure trend was flagged for review in the synthetic daily report; it is not a calibrated pore-pressure estimate.",
        "md": 2190,
        "tvd": 2001,
        "formation": "y",
        "date": "2023-06-17T08:10:00Z",
        "consequence": "The recorded operation included an additional verification pause.",
        "mitigation": "The report notes repeat checks and engineer review of the observed trend.",
        "severity": "medium",
        "page": 10,
        "confidence": 0.88,
        "evidence": "Representative Synthetic Demo Data: elevated pressure trend flagged for review near 2,190 m; repeat checks noted.",
    },
    {
        "key": "ANB-06-drag-1320",
        "well": "ANB-06",
        "type": "drag_increase",
        "title": "Drag increase in Y Shale",
        "description": "An earlier interval records a modest increase in pickup drag above the current section.",
        "md": 1320,
        "tvd": 1208,
        "formation": "y",
        "date": "2026-08-29T03:35:00Z",
        "consequence": "The connection sequence required additional monitoring.",
        "mitigation": "The crew documented a circulation check and monitored movement before resuming.",
        "severity": "low",
        "page": 14,
        "confidence": 0.91,
        "evidence": "Representative Synthetic Demo Data: drag increase at 1,320 m in Y Shale; circulation check recorded.",
    },
    {
        "key": "ANB-07-stuck-1932",
        "well": "ANB-07",
        "type": "stuck_pipe",
        "title": "Stuck pipe event in Z Sandstone",
        "description": "A stuck-pipe event was documented while moving through Z Sandstone.",
        "md": 1932,
        "tvd": 1774,
        "formation": "z",
        "date": "2023-02-12T09:20:00Z",
        "consequence": "The string could not initially be moved and non-productive time was recorded.",
        "mitigation": "The report records working the string and circulation while monitoring loads.",
        "severity": "high",
        "page": 25,
        "confidence": 0.96,
        "evidence": "Representative Synthetic Demo Data: stuck pipe at 1,932 m in Z Sandstone; string-working response documented.",
    },
    {
        "key": "ANB-07-fishing-1945",
        "well": "ANB-07",
        "type": "fishing_operation",
        "title": "Fishing operation after tool-string separation",
        "description": "A separate synthetic event record documents a fishing operation following tool-string separation.",
        "md": 1945,
        "tvd": 1786,
        "formation": "z",
        "date": "2023-02-13T16:50:00Z",
        "consequence": "Fishing operations extended the recorded non-productive period.",
        "mitigation": "The historical summary records a fishing assembly run and recovered item confirmation.",
        "severity": "high",
        "page": 27,
        "confidence": 0.92,
        "evidence": "Representative Synthetic Demo Data: fishing operation near 1,945 m in Z Sandstone; recovered item noted.",
    },
    {
        "key": "ANB-07-npt-1932",
        "well": "ANB-07",
        "type": "npt_event",
        "title": "Non-productive time associated with stuck pipe",
        "description": "The final synthetic report classifies the time spent addressing the stuck-pipe event as NPT.",
        "md": 1932,
        "tvd": 1774,
        "formation": "z",
        "date": "2023-02-12T09:20:00Z",
        "consequence": "The event contributed to the offset well's recorded NPT.",
        "mitigation": "The final report links the recorded NPT to the crew's string-working response.",
        "severity": "medium",
        "page": 70,
        "confidence": 0.94,
        "evidence": "Representative Synthetic Demo Data: NPT category linked to the 1,932 m stuck-pipe event.",
    },
    {
        "key": "ANB-08-cleaning-1120",
        "well": "ANB-08",
        "type": "hole_cleaning_issue",
        "title": "Cuttings loading in Upper Shale",
        "description": "A short earlier interval records increased cuttings at surface above Y Shale.",
        "md": 1080,
        "tvd": 982,
        "formation": "upper",
        "date": "2026-09-10T12:00:00Z",
        "consequence": "The drilling sequence paused for additional circulation.",
        "mitigation": "The crew recorded circulation and returns monitoring before resuming.",
        "severity": "low",
        "page": 9,
        "confidence": 0.90,
        "evidence": "Representative Synthetic Demo Data: cuttings loading at 1,080 m in Upper Shale; circulation response recorded.",
    },
    {
        "key": "ANB-09-cement-1560",
        "well": "ANB-09",
        "type": "cementing_issue",
        "title": "Cement returns below expected volume at casing shoe",
        "description": "The daily report records lower-than-expected cement returns during a casing cement job across Y Shale.",
        "md": 1560,
        "tvd": 1438,
        "formation": "y",
        "date": "2024-10-26T05:55:00Z",
        "consequence": "The cementing operation required additional evaluation and time.",
        "mitigation": "The report records a wait-on-cement period, pressure test, and documented engineering review.",
        "severity": "medium",
        "page": 21,
        "confidence": 0.95,
        "evidence": "Representative Synthetic Demo Data: cement returns below expected volume near 1,560 m across Y Shale; follow-up evaluation noted.",
    },
    {
        "key": "ANB-09-casing-1530",
        "well": "ANB-09",
        "type": "casing_issue",
        "title": "Casing running resistance above the Y Shale shoe",
        "description": "A casing-running delay was recorded shortly before reaching the planned shoe depth.",
        "md": 1530,
        "tvd": 1411,
        "formation": "y",
        "date": "2024-10-25T18:20:00Z",
        "consequence": "The run took additional time and the cementing schedule shifted.",
        "mitigation": "The historical entry notes a controlled pullback, circulation, and monitored continuation.",
        "severity": "medium",
        "page": 19,
        "confidence": 0.91,
        "evidence": "Representative Synthetic Demo Data: casing running resistance near 1,530 m in Y Shale; controlled response described.",
    },
    {
        "key": "ANB-10-drag-1780",
        "well": "ANB-10",
        "type": "drag_increase",
        "title": "Earlier drag trend in Z Sandstone",
        "description": "An earlier section records a brief drag increase well above the current Basal Sandstone interval.",
        "md": 1780,
        "tvd": 1630,
        "formation": "z",
        "date": "2026-09-24T06:15:00Z",
        "consequence": "A short monitored pause was recorded.",
        "mitigation": "The daily report notes circulation and a monitored movement check before continuing.",
        "severity": "low",
        "page": 10,
        "confidence": 0.90,
        "evidence": "Representative Synthetic Demo Data: earlier drag trend at 1,780 m in Z Sandstone; no comparable event at current depth noted.",
    },
]


ALERT_FIXTURES: List[Dict[str, Any]] = [
    {"active": "ANB-01", "event": "ANB-02-loss-2865", "score": 91.0},
    {"active": "ANB-01", "event": "ANB-03-torque-2830", "score": 86.0},
    {"active": "ANB-01", "event": "ANB-04-loss-2875", "score": 88.0},
    {"active": "ANB-06", "event": "ANB-07-stuck-1932", "score": 90.0},
    {"active": "ANB-08", "event": "ANB-09-cement-1560", "score": 87.0},
]

DEMO_SCENARIOS = {
    "X Formation historical match": {"active": "ANB-01", "offsets": ["ANB-02", "ANB-03", "ANB-04"]},
    "Stuck pipe precedent": {"active": "ANB-06", "offsets": ["ANB-07"]},
    "Cementing precedent": {"active": "ANB-08", "offsets": ["ANB-09"]},
    "No significant historical match": {"active": "ANB-10", "nearby_offset": "ANB-09"},
}
